In [2]:
import numpy as np
import pandas as pd

from datetime import datetime, timedelta
import os
from time import sleep
import json
import re

import warnings
warnings.filterwarnings("ignore")

import pickle as pkl

from pprint import pprint

from libraries.preprocess import preprocess

In [3]:
%%time

# Lee todos los archivos de la carpeta de "json_searches_spain"
# Crea una lista con los json

FOLDER_PATH = "json_searches_spain/" 

files = os.listdir(FOLDER_PATH)
jobs_results = list()
search_date = list()

for file in files:
    
    with open(file = f"{FOLDER_PATH}{file}", mode = "r") as f:
        x = json.load(f)
        
    if "jobs_results" in x:
        jobs_results.extend(x["jobs_results"])
        
        if "search_metadata" in x:
            date = x["search_metadata"]["created_at"]
            date = datetime.strptime(x["search_metadata"]["created_at"], "%Y-%m-%d %H:%M:%S UTC").date()
            
            for i in range(len(x["jobs_results"])):
                search_date.append(date)
    
print(len(jobs_results))
print(len(search_date))

86329
86329
CPU times: total: 4.12 s
Wall time: 6.25 s

In [4]:
df = pd.json_normalize(jobs_results)

del jobs_results

df["date_posted"] = search_date

df.shape

(86329, 15)

In [5]:
df = df.drop_duplicates("job_id").reset_index(drop = True)

df.shape

(86168, 15)

In [6]:
df = df.drop_duplicates("description").reset_index(drop = True)

df.shape

(22194, 15)

In [7]:
%%time

# Eliminamos duplicados
df = df.drop_duplicates("job_id").reset_index(drop = True) 

# Limpiamos "via"
for i in range(len(df["via"])):
    
    # Debido a valores NoneType, usamos try/except
    
    try:
        df.loc[i, "via"] = preprocess.clean_source(df.loc[i, "via"]) # Cada fila
        
    except:
        df.loc[i, "via"] = np.nan
    
# Limpiamos "location"
df["location"] = df["location"].apply(lambda x : preprocess.clean_location(x))

# Limpiamos "contract_type"
df["detected_extensions.schedule_type"] = df["detected_extensions.schedule_type"].apply(lambda x : preprocess.clean_contract_type(x))

# Limpiamos "created_date"
df["detected_extensions.posted_at"] = df["detected_extensions.posted_at"].apply(lambda x : preprocess.transform_date(x))

df["date_posted"] = [preprocess.get_date(x, y) for x, y in df[["date_posted", "detected_extensions.posted_at"]].values]

tech_skills = list()

# Creamos "tech_skills"
for i in range(df["description"].shape[0]):
    
    if not pd.isna(df.loc[i, "description"]):
    
    # try:
        tech_skills.append(preprocess.get_skills(df.loc[i, "description"])) # Cada fila
        
    else:
        tech_skills.append(np.nan)
        
df["tech_skills"] = tech_skills

CPU times: total: 4min 1s
Wall time: 17min 4s

In [8]:
df

,title,company_name,location,via,description,job_highlights,related_links,extensions,job_id,detected_extensions.posted_at,detected_extensions.schedule_type,thumbnail,detected_extensions.work_from_home,detected_extensions.salary,date_posted,tech_skills
0,Desarrollador de Software,THE WISE SEEKER S.L,Spain,Infoempleo,- Desarrollar soluciones de software asegurand...,[{'items': ['- Desarrollar soluciones de softw...,"[{'link': 'http://www.thewiseseeker.com/', 'te...","[17 hours ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,0 days 17:00:00,Full-time,NaN,NaN,NaN,2024-04-17,[]
1,Desarrollador de Software,WITRON Logistik + Informatik GmbH,"Madrid, Spain",Glassdoor,Als Teil der WITRON Gruppe plant und realisier...,[{'items': ['Als Teil der WITRON Gruppe plant ...,"[{'link': 'http://www.witron.de/', 'text': 'wi...","[28 days ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,28 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-03-20,[SQL]
2,Desarrollador de software,CBT,"Getxo, Spain",LinkedIn,CBT es una empresa del Grupo Innovalia dedicad...,[{'items': ['CBT es una empresa del Grupo Inno...,[{'link': 'https://www.google.com/search?sca_e...,"[2 days ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIHNvZn...,2 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-15,"[Angular, Android, iPhone]"
3,Desarrollador/a de software en C/C+,SEGULA Technologies,"Barcelona, Spain",LinkedIn,Localidad : Barcelona\n\nProvincia : Barcelona...,[{'items': ['Localidad : Barcelona Provincia ...,[{'link': 'http://www.segulatechnologies.com/'...,"[2 days ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yL2EgZGUgc2...,2 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-15,"[Jira, REST]"
4,Desarrollador de PHP,Proconsi,"León, Spain",LinkedIn,𝐏𝐫𝐨𝐠𝐫𝐚𝐦𝐚𝐝𝐨𝐫𝐞𝐬/𝐚𝐬 𝐏𝐇𝐏 𝐋𝐀𝐑𝐀𝐕𝐄𝐋 👩💻 👨💻\n\n¿𝐏𝐫𝐨𝐠𝐫𝐚𝐦...,[{'items': ['𝐏𝐫𝐨𝐠𝐫𝐚𝐦𝐚𝐝𝐨𝐫𝐞𝐬/𝐚𝐬 𝐏𝐇𝐏 𝐋𝐀𝐑𝐀𝐕𝐄𝐋 👩💻 👨...,"[{'link': 'http://www.proconsi.com/', 'text': ...","[1 day ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFBIUC...,1 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-16,"[CSS, JavaScript, JSON, PHP, Javascript]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Analista Programador Dynamics (CRM),X25 Informática S.L.,"Madrid, Spain",LinkedIn,Buscamos un Desarrollador Dynamics CRM para co...,[{'items': ['Buscamos un Desarrollador Dynamic...,[{'link': 'https://www.google.com/search?sca_e...,"[7 hours ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBQcm9ncmFtYWRvci...,0 days 07:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-29,"[SQL, CRM, Dynamics]"
22190,Científico/a de Datos,ASOCIACION PARA EL DESARROLLO DE LA INGENIERIA...,Spain,Glassdoor,¿Qué te pedimos?\n• Doble titulación en Ingeni...,[{'items': ['¿Qué te pedimos? • Doble titulaci...,[{'link': 'https://www.google.com/search?sca_e...,"[25 days ago, Full-time]",eyJqb2JfdGl0bGUiOiJDaWVudMOtZmljby9hIGRlIERhdG...,25 days 00:00:00,Full-time,NaN,NaN,NaN,2024-04-04,"[Aceptación, GitHub, DOS]"
22191,Informático a domicilio para configurar equipo...,Cronoshare,"San Lorenzo de El Escorial, Spain",BeBee,Necesito un servicio de Informático a domicili...,[{'items': ['Necesito un servicio de Informáti...,[{'link': 'https://www.google.com/search?sca_e...,"[4 days ago, Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJJbmZvcm3DoXRpY28gYSBkb21pY2...,4 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-25,[]
22192,Inside Technician TCS,Diversey,"Viladecans, Spain",BeBee,Responsabilidades:\n\nResponsable del soporte ...,[{'items': ['Responsabilidades: Responsable d...,"[{'link': 'http://www.diversey.com/', 'text': ...","[4 days ago, Full-time]",eyJqb2JfdGl0bGUiOiJJbnNpZGUgVGVjaG5pY2lhbiBUQ1...,4 days 00:00:00,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-25,"[ERP, Microsoft, SAP]"
22193,Analista de seguridad intune/mdm,Cas Training,"Madrid, Spain",Worksinit,"Cas-Training, empresa de referencia con más de...","[{'items': ['Cas-Training, empresa de referenc...",[{'link': 'https://www.google.com/search?sca_e...,"[Full-time, No degree mentioned]",eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBkZSBzZWd1cmlkYW...,NaT,Full-time,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,NaN,2024-04-29,"[Azure, Prisma]"

In [9]:
preprocess.get_skills(df[df["title"] == "Científico/a de Datos"]["description"][22190])

['Aceptación', 'GitHub', 'DOS']

In [10]:
df.iloc[22190,:]

title                                                             Científico/a de Datos
company_name                          ASOCIACION PARA EL DESARROLLO DE LA INGENIERIA...
location                                                                          Spain
via                                                                           Glassdoor
description                           ¿Qué te pedimos?\n• Doble titulación en Ingeni...
job_highlights                        [{'items': ['¿Qué te pedimos?
• Doble titulaci...
related_links                         [{'link': 'https://www.google.com/search?sca_e...
extensions                                                     [25 days ago, Full-time]
job_id                                eyJqb2JfdGl0bGUiOiJDaWVudMOtZmljby9hIGRlIERhdG...
detected_extensions.posted_at                                          25 days 00:00:00
detected_extensions.schedule_type                                             Full-time
thumbnail                                                                           NaN
detected_extensions.work_from_home                                                  NaN
detected_extensions.salary                                                          NaN
date_posted                                                                  2024-04-04
tech_skills                                                   [Aceptación, GitHub, DOS]
Name: 22190, dtype: object

In [11]:
df["tech_skills"].value_counts()

tech_skills
[]                                                                                 5580
[Integración]                                                                       475
[SAP]                                                                               366
[DOS]                                                                               273
[Marketing]                                                                         232
                                                                                   ...
[CSS, DB2, Funcionales, Integración, jQuery, Kanban, Oracle, Scrum, Sonar, SQL]       1
[Funcionales, Integración, Marketing]                                                 1
[Java, Twitter]                                                                       1
[Jira, Oracle, SQL, SAS, Training]                                                    1
[Azure, Prisma]                                                                       1
Name: count, Length: 8874, dtype: int64

In [12]:
def clean_column_names(df):
    
    mapper = {"via"                               : "source",
              "detected_extensions.schedule_type" : "contract_type"}
    
    df = df.rename(mapper = mapper, axis = 1)    
    return df

In [13]:
# Renombramos los nombres de las columnas
df = clean_column_names(df)
# Nos quedamos con las columnas que nos interesan
df = df[["job_id", "title", "company_name", "location", "source",
         "description", "date_posted", "contract_type", "tech_skills"]]

df.shape

(22194, 9)

In [14]:
df

,job_id,title,company_name,location,source,description,date_posted,contract_type,tech_skills
0,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,Desarrollador de Software,THE WISE SEEKER S.L,Spain,Infoempleo,- Desarrollar soluciones de software asegurand...,2024-04-17,Full-time,[]
1,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,Desarrollador de Software,WITRON Logistik + Informatik GmbH,"Madrid, Spain",Glassdoor,Als Teil der WITRON Gruppe plant und realisier...,2024-03-20,Full-time,[SQL]
2,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIHNvZn...,Desarrollador de software,CBT,"Getxo, Spain",LinkedIn,CBT es una empresa del Grupo Innovalia dedicad...,2024-04-15,Full-time,"[Angular, Android, iPhone]"
3,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yL2EgZGUgc2...,Desarrollador/a de software en C/C+,SEGULA Technologies,"Barcelona, Spain",LinkedIn,Localidad : Barcelona\n\nProvincia : Barcelona...,2024-04-15,Full-time,"[Jira, REST]"
4,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFBIUC...,Desarrollador de PHP,Proconsi,"León, Spain",LinkedIn,𝐏𝐫𝐨𝐠𝐫𝐚𝐦𝐚𝐝𝐨𝐫𝐞𝐬/𝐚𝐬 𝐏𝐇𝐏 𝐋𝐀𝐑𝐀𝐕𝐄𝐋 👩💻 👨💻\n\n¿𝐏𝐫𝐨𝐠𝐫𝐚𝐦...,2024-04-16,Full-time,"[CSS, JavaScript, JSON, PHP, Javascript]"
...,...,...,...,...,...,...,...,...,...
22189,eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBQcm9ncmFtYWRvci...,Analista Programador Dynamics (CRM),X25 Informática S.L.,"Madrid, Spain",LinkedIn,Buscamos un Desarrollador Dynamics CRM para co...,2024-04-29,Full-time,"[SQL, CRM, Dynamics]"
22190,eyJqb2JfdGl0bGUiOiJDaWVudMOtZmljby9hIGRlIERhdG...,Científico/a de Datos,ASOCIACION PARA EL DESARROLLO DE LA INGENIERIA...,Spain,Glassdoor,¿Qué te pedimos?\n• Doble titulación en Ingeni...,2024-04-04,Full-time,"[Aceptación, GitHub, DOS]"
22191,eyJqb2JfdGl0bGUiOiJJbmZvcm3DoXRpY28gYSBkb21pY2...,Informático a domicilio para configurar equipo...,Cronoshare,"San Lorenzo de El Escorial, Spain",BeBee,Necesito un servicio de Informático a domicili...,2024-04-25,Full-time,[]
22192,eyJqb2JfdGl0bGUiOiJJbnNpZGUgVGVjaG5pY2lhbiBUQ1...,Inside Technician TCS,Diversey,"Viladecans, Spain",BeBee,Responsabilidades:\n\nResponsable del soporte ...,2024-04-25,Full-time,"[ERP, Microsoft, SAP]"
22193,eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBkZSBzZWd1cmlkYW...,Analista de seguridad intune/mdm,Cas Training,"Madrid, Spain",Worksinit,"Cas-Training, empresa de referencia con más de...",2024-04-29,Full-time,"[Azure, Prisma]"

In [15]:
# Funciones para generar las columnas de años de experiencia y nivel de experiencia
def find_years_of_experience(string: str):
    
    list_strings = ["años de", "years of", "years experience", "años experiencia"]
    
    string = string.lower()
    
    years = [string[string.find(s) - 5 : string.find(s) + len(s) + 1] for s in list_strings if string.find(s) != -1]
    
    numeros = [re.findall(r"\d+", y) for y in years]

    numeros = [[int(n) for n in num if 0 < int(n) < 13] for num in numeros]
    
    numeros = [max(num) if num else np.nan for num in numeros]

    return max(numeros) if numeros else np.nan


def experience_level(num):
    
    if not pd.isna(num):
    
        if num < 2:
            return "Junior"
        elif num <= 4:
            return "Semi-Senior"
        elif num < 8:
            return "Senior"
        else:
            return "Leader"
        
    else:
        return np.nan

In [16]:
df["experience"] = df["description"].apply(lambda x : find_years_of_experience(x) if not pd.isna(x) else x)
df["experience_level"] = df["experience"].apply(lambda x : experience_level(x))

In [17]:
# Actualizamos "contract_type"
df["contract_type"] = df["contract_type"]\
                            .apply(lambda x : "Full-time" if x == "Tiempo completo" else x)

# Creamos "remote_work"
def get_remote_work(string):
    
    resultados = list()
    
    if "remoto" in string or "remote work" in string or "remote" in string:
        
        resultados.append("Remoto")
        
    elif "hibrido" in string or "hybrid" in string or "híbrido" in string:
        
        resultados.append("Hibrido")
        
    elif "presencial" in string or "in-office" in string:
        
        resultados.append("Presencial")
        
    else:
        return np.nan
        
    return resultados

df["remote_work"] = df["description"].apply(lambda x : get_remote_work(x))

# Actualizamos "location"
# ¡PENDIENTE, CONSULTAR CON DANI!
# ACTUALIZADO en la librería de preprocesamiento para el pipeline

In [18]:
df

,job_id,title,company_name,location,source,description,date_posted,contract_type,tech_skills,experience,experience_level,remote_work
0,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,Desarrollador de Software,THE WISE SEEKER S.L,Spain,Infoempleo,- Desarrollar soluciones de software asegurand...,2024-04-17,Full-time,[],NaN,NaN,NaN
1,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFNvZn...,Desarrollador de Software,WITRON Logistik + Informatik GmbH,"Madrid, Spain",Glassdoor,Als Teil der WITRON Gruppe plant und realisier...,2024-03-20,Full-time,[SQL],NaN,NaN,NaN
2,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIHNvZn...,Desarrollador de software,CBT,"Getxo, Spain",LinkedIn,CBT es una empresa del Grupo Innovalia dedicad...,2024-04-15,Full-time,"[Angular, Android, iPhone]",NaN,NaN,NaN
3,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yL2EgZGUgc2...,Desarrollador/a de software en C/C+,SEGULA Technologies,"Barcelona, Spain",LinkedIn,Localidad : Barcelona\n\nProvincia : Barcelona...,2024-04-15,Full-time,"[Jira, REST]",3.0,Semi-Senior,NaN
4,eyJqb2JfdGl0bGUiOiJEZXNhcnJvbGxhZG9yIGRlIFBIUC...,Desarrollador de PHP,Proconsi,"León, Spain",LinkedIn,𝐏𝐫𝐨𝐠𝐫𝐚𝐦𝐚𝐝𝐨𝐫𝐞𝐬/𝐚𝐬 𝐏𝐇𝐏 𝐋𝐀𝐑𝐀𝐕𝐄𝐋 👩💻 👨💻\n\n¿𝐏𝐫𝐨𝐠𝐫𝐚𝐦...,2024-04-16,Full-time,"[CSS, JavaScript, JSON, PHP, Javascript]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
22189,eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBQcm9ncmFtYWRvci...,Analista Programador Dynamics (CRM),X25 Informática S.L.,"Madrid, Spain",LinkedIn,Buscamos un Desarrollador Dynamics CRM para co...,2024-04-29,Full-time,"[SQL, CRM, Dynamics]",NaN,NaN,NaN
22190,eyJqb2JfdGl0bGUiOiJDaWVudMOtZmljby9hIGRlIERhdG...,Científico/a de Datos,ASOCIACION PARA EL DESARROLLO DE LA INGENIERIA...,Spain,Glassdoor,¿Qué te pedimos?\n• Doble titulación en Ingeni...,2024-04-04,Full-time,"[Aceptación, GitHub, DOS]",NaN,NaN,NaN
22191,eyJqb2JfdGl0bGUiOiJJbmZvcm3DoXRpY28gYSBkb21pY2...,Informático a domicilio para configurar equipo...,Cronoshare,"San Lorenzo de El Escorial, Spain",BeBee,Necesito un servicio de Informático a domicili...,2024-04-25,Full-time,[],NaN,NaN,[Remoto]
22192,eyJqb2JfdGl0bGUiOiJJbnNpZGUgVGVjaG5pY2lhbiBUQ1...,Inside Technician TCS,Diversey,"Viladecans, Spain",BeBee,Responsabilidades:\n\nResponsable del soporte ...,2024-04-25,Full-time,"[ERP, Microsoft, SAP]",NaN,NaN,[Remoto]
22193,eyJqb2JfdGl0bGUiOiJBbmFsaXN0YSBkZSBzZWd1cmlkYW...,Analista de seguridad intune/mdm,Cas Training,"Madrid, Spain",Worksinit,"Cas-Training, empresa de referencia con más de...",2024-04-29,Full-time,"[Azure, Prisma]",NaN,NaN,NaN

In [19]:
def clean_location_spain(x):
    
    if type(x) == str:
        
        if x == "Spain":
            return "Spain"
        
        elif x == "Anywhere":
            return "Anywhere"
        
        if "," in x:
            
            x = x.split(", ")[0]
            
            if x == "Community of Madrid":
                return "Madrid"
            
            return x
        
    return np.nan

In [20]:
df["location"] = df["location"].apply(lambda x : clean_location_spain(x))

In [21]:
df["location"].value_counts(dropna = False, normalize = True)

location
Madrid        0.317023
Anywhere      0.144499
Barcelona     0.106515
Spain         0.098991
Valencia      0.027260
                ...
Canovelles    0.000045
Montilla      0.000045
La Zubia      0.000045
Santa Pola    0.000045
Monte         0.000045
Name: proportion, Length: 812, dtype: float64

In [22]:
def eliminar_caracteres_especiales(x):
    patron = r"[^\w\s]"
    return re.sub(patron, "", x)

# Empresas

In [24]:
df_company = pd.read_csv("empresas_v1.csv").dropna().reset_index(drop = True)

df_company["company_name_lower"] = df_company["company_name"].apply(lambda x : x.lower())
df_company["company_name_lower_no_spaces"] = df_company["company_name_lower"].apply(lambda x : x.replace(" ", ""))
df_company["company_name_lower_no_spaces_no_special_char"] = df_company["company_name_lower_no_spaces"].apply(lambda x : eliminar_caracteres_especiales(x))

df_company

,company_name,company_name_lower,company_name_lower_no_spaces,company_name_lower_no_spaces_no_special_char
0,THE WISE SEEKER S.L,the wise seeker s.l,thewiseseekers.l,thewiseseekersl
1,WITRON Logistik + Informatik GmbH,witron logistik + informatik gmbh,witronlogistik+informatikgmbh,witronlogistikinformatikgmbh
2,CBT,cbt,cbt,cbt
3,SEGULA Technologies,segula technologies,segulatechnologies,segulatechnologies
4,Proconsi,proconsi,proconsi,proconsi
...,...,...,...,...
4805,Came Parkare,came parkare,cameparkare,cameparkare
4806,PROYECSON,proyecson,proyecson,proyecson
4807,Acrelec,acrelec,acrelec,acrelec
4808,Ctrl360,ctrl360,ctrl360,ctrl360
4809,"INNOVACIÓN Y CUALIFICACIÓN, S.L.","innovación y cualificación, s.l.","innovaciónycualificación,s.l.",innovaciónycualificaciónsl

In [25]:
def levenshtein_distance(str1, str2):

    d = dict()
    
    for i in range(len(str1)+1):
        
        d[i]=dict()
        d[i][0]=i
        
    for i in range(len(str2)+1):
        
        d[0][i] = i
        
    for i in range(1, len(str1)+1):
        for j in range(1, len(str2)+1):
            
            d[i][j] = min(d[i][j-1]+1, d[i-1][j]+1, d[i-1][j-1]+(not str1[i-1] == str2[j-1]))
            
            
    return d[len(str1)][len(str2)]

In [26]:
# Sacamos las compañias del df de extracción y transformamos a minusculas sin espacios y sin caracteres especiales

companies = list({eliminar_caracteres_especiales(x.lower().replace(" ", "")) for x in df["company_name"].unique()})

len(companies)

6289

In [27]:
companies

['telefónicatechgovertis',
 'ilunion',
 'turnertownsend',
 'ctrl360',
 'abalia',
 'riekatalentett',
 'aimhiregloballtd',
 'airtificialaerospacedefense',
 'enerlandgroup',
 'centricsoftware',
 'trentiaconsulting',
 'ednon',
 'cumminscareers',
 'hdivsecurity',
 'rocasalvatella',
 'cwelltsoftwaresl',
 'sesameuniverse_',
 'gruporetabet',
 'invenergy',
 'arvatosupplychainsolutions',
 'inetum',
 'vatesanepamcompany',
 'openassessmenttechnologiessa',
 'zitro',
 'aszendittech',
 'helphone',
 'talenthunter',
 'utopiux',
 'anecoopscoop',
 'magtel',
 'grupoamper',
 'atentoespaña',
 'grupoespiral',
 'abbschweizag',
 'clienterandstad',
 'capitalempresarialhorizonte',
 'metyis',
 'trentia',
 'gruposurmaster',
 'techstaq',
 'coresystemsserviciosysoluciones',
 'enrique',
 'cornerjobstaffing',
 'sermica',
 'universae',
 'grupovolmae',
 'acquirehrsolutions',
 'cunovesagroup',
 'artworkscomunicación',
 'alejandra',
 'academiageorgetown',
 'esmlsdiberiaholdingsau',
 'dimaimsystemssl',
 'panelsistemasinformaticos',
 'grandhotelcentral',
 'manpowergrouptalentsolutions',
 'cosermo',
 'eposspain',
 'musgraveespaña',
 'superespot',
 'ceciliamentacordobacórdoba',
 'strategybigdata',
 'bnpparibascorporateinstitutionalbanking',
 'urbaser',
 'adegilan',
 'aciertocom',
 'openonmondays',
 'veoliaenvironnement',
 'talent40ba',
 'diverselynx',
 'basaloarquitectosslp',
 'mindden',
 'aszende',
 'orbidi',
 'concentrioag',
 'keyrus',
 'acesur',
 'smservices',
 'startenautomationsolutions',
 'm47labs',
 'vilarriba',
 'nextpymeserviciosinformáticos',
 'fundaciononce',
 'siemensgasandpowergmbhcokg',
 'anonimo',
 'marcotrantransportesinternacionalessl',
 'squirrelmedia',
 'residencialesmovilessa',
 'leroymerlinespaña',
 'outvise',
 'ryanairltd',
 'llorenteycuenca',
 'fintonic',
 'sclconsulting',
 'importanteescueladenegociosyconsultoradeformación',
 'larraioz',
 'crit',
 'movistarproseguralarmas',
 'telec21',
 'trisquelproteccionyvigilanciasa',
 'apexamerica',
 'foshtech',
 'changetheblock',
 'best4up',
 'seragroup',
 'bluselectionrecruitmentagency',
 'dimaticasoftwaredevelopment',
 'fervimax',
 'excibitsolutionsspain',
 'hiretech',
 'asertiglobalsolutions',
 'eventosmágicosmadrid',
 'gijón',
 'atmiraspain',
 'sexpe',
 'serviclients',
 'ppd',
 'euskojaurlaritzareninformatikaelkarteaejie',
 'flowable',
 'doymus',
 'pwcespaña',
 'dosenesmarketingonlineysoftware',
 'synatix',
 'experisespaña',
 'sembogroup',
 'clarcatconsultingsal',
 'instelcasl',
 'groupmecalux',
 'capitalenergy',
 'omnios',
 'santalucíagroup',
 'etalentumgarrotxaripollès',
 'i3eitresources',
 'trimbleinc',
 'unatecict',
 'bdospain',
 'norconsultingglobalrecruitment',
 'bewortech',
 'tüvrheinland',
 'globalhumancapitalgroup',
 'publicadaperettagenciarrhh',
 'sygris',
 'losgratuitos',
 'hubceu',
 'smartdreamsl',
 'lookingfortalentconsultores',
 'evaortegagimenez',
 'jrspain',
 'deloitteempleo',
 'allerstechnology',
 'managementsolutions',
 'abox',
 'rayco',
 'cámaradecomerciodeciudadreal',
 'qubiq',
 'kleinslidingdoorsystems',
 'empresaconpresenciainternacionalquellevamásde35añosdesarrollandoproyectosdeingenieríaarquitecturaconsultoríaestratégicaytecnologíasdelainformaciónparaelsectordetransportes',
 'bigblue',
 'glory',
 'aldsistemas',
 'seguridadaeroportuaria',
 'hotelesposeidon',
 'carnect',
 'yourtalentside',
 'multinacionalfrancesalíderespecializadaenserviciosdeconsultoríadelafinanciacióndelainnovación',
 'intagralis',
 'ge',
 'kingmakers',
 'grupoortiz',
 'scalers',
 'penguinrandomhousegrupoeditorialsau',
 'afimagen',
 'obsstechnology',
 'forjaideascreativasdecomunicaciónsl',
 'axactorspain',
 'barcodemarket',
 'scalian',
 'musicdistribución',
 'jitrixsoftwaredesign',
 'cidetec',
 'isginternationalservicegroup',
 'fundaciónuniversidadempresa',
 'tempotelett',
 'ziorem',
 'movilges',
 'redhospitalariarecoletas',
 'novatiumcordobacórdoba',
 'iscaremhumanresources',
 'omegacrmamerklecompany',
 'univrse',
 'efeducationfirst',
 'ana',
 'helphoneserviciosinformáticos',
 'telnyx',
 'crossbordertalents',
 'universidadnebrija',
 'obtindu',
 'nucliotalent',
 'scandit',
 'prismalia',
 'reparacionlcd',
 'goldenrace',
 'clarcat',
 'dibalsolucionesdepesajeyetiquetadoparacomercioeindustriabalanzasyequiposautomáticos',
 'josemariafernandez',
 'postgradoenodontologiasociedadlimitada',
 'minsait',
 'ubisoft',
 'histocellregenerativemedicine',
 'saturnaliashow',
 'etalentumselección',
 'axouxereinformaticasl',
 'serena',
 'devoteamspain',
 'aegon',
 'huang',
 'pwc',
 'imagina',
 'tsetechnologysolutions',
 'signaturit',
 'phiosag',
 'automaatiosl',
 'libelium',
 'kaptiagestióndetalento',
 'flopwork',
 'comicstudio',
 'quandumaerospace',
 'empatizaconsulting',
 'linkogroup',
 'nazaríesintelligenia',
 'nippongases',
 'inadesojustsl',
 'aerotecnic',
 'aspasluagrupacióndeserviciosyproductosdeaudio',
 'six',
 'denemaxconsulting',
 'teldat',
 'antolin',
 'infortecconsultores',
 'ring',
 'legálitas',
 'edicom',
 'atlastecnológico',
 'typsa',
 'workfully',
 'publiupagenciademarketingdigital',
 'innoit',
 'apifema',
 'futuraetechnologiesag',
 'velocitytech',
 'mainpapersl',
 'vastbouw',
 'jellyfishgroup',
 'rgzdevelopers',
 'servcordsc',
 'scopic',
 'lacasadelascarcasas',
 'pcclinicmérida',
 'galgus',
 'veneciaitheadhunter',
 'indistaffingservices',
 'neticscommunications',
 'zaidanitsolutions',
 'aatconsultoriadeproyectos',
 'touchintouch',
 'sorigué',
 'electroal',
 'viasat',
 'brgi',
 'bostonscientific',
 'clevertask',
 'luxen',
 'william',
 'omegaperipherals',
 'lidl',
 'mandarinorientalhotelgroup',
 'ethermail',
 'tier1sa',
 'openreferences',
 'grupomb',
 'engelvölkerscommercialmadrid',
 'grupoioe',
 'hiringit',
 'grupodiseñosnt',
 'steelmoodeurope',
 'eurovisionservices',
 'vassuki',
 'idoia',
 'aulacampus',
 'exxita',
 'empresadeingenieria',
 'ongres',
 'contentsquare',
 'oxigenttechnologies',
 'amcnaturaldrinks',
 'desarrollosdesoftwareyweb',
 'amazonspainfulfillmentslu',
 'dlocal',
 'fmittechnologiessl',
 'hiring',
 'avaloratecnologíasdelainformación',
 'celia',
 'paginaweb',
 'aulacreactiva',
 'ondabradio',
 'powerelectronicsespañasl',
 'altair',
 'embention',
 'airup',
 'fischeribérica',
 'aname',
 'servitalent',
 'sherpany',
 'autentiabyizertis',
 'personasyestrategia',
 'cognizanttechnologysolutions',
 'jose',
 'blotodocursos',
 'webhelp',
 'ingenia',
 'proyectaconsultorestic',
 'micropole',
 'spbthespbglobalcorporation',
 'expertiseheadhunters',
 'ayscom',
 '314financialcontents',
 'grupoindustriassaludes',
 'empresadelsectorserviciossociales',
 'allot',
 'bondex',
 'duitstudio',
 'dhrglobal',
 'klikin',
 'sciserviclientsinformáticasl',
 'vócali',
 'gruposaf',
 'bertrandtgroup',
 'nexttic',
 'gramgroupsistemasdepesaje',
 'olybetgroup',
 'pinchaaqui',
 'garotecnia',
 'fossilgroupinc',
 'roadsurfer',
 'tickendy',
 'sarartesl',
 'kosmos',
 'gfkgrowthfromknowledge',
 'casinogranmadrid',
 'brainboxgroup',
 'seneraerospacedefence',
 'duagon',
 'payfitfrance',
 'nartexsoftware',
 'ander',
 'netdriver',
 'mongodb',
 'lucca',
 'between',
 'bankinterglobalservicessa',
 'oliverjamesassociates',
 'gloin',
 'departamentogallegodeinformática',
 'recruitmentsolutions',
 'rótulosmetalarte',
 'cronosharecom',
 'minsaitindrasolucionesti',
 'rpo',
 'isoiningenieríaysolucionesinformáticasdelsur',
 'edisa',
 'qukiqvialtd',
 'grupodeingenieríamundial',
 'internetmarketing',
 'allerganaesthetics',
 'farmaciastrébolsl',
 'doméstikocom',
 'tufabricadeventos',
 'nodisponible',
 'rattixmotors',
 'gruporfranco',
 'israelvillarencontrareimpulsarpersonas',
 'telemailsl',
 'jobfinderspain',
 'evolution',
 'empresadetelecomunicaciones',
 'ascensiumconsultores',
 'ingivasc',
 'ustlogisticalsystems',
 'josemiguel',
 'launchmetrics',
 'ailylabs',
 'odemespaña',
 'elemaringenieros',
 'siemenshealthineers',
 'mangopay',
 'gubseag',
 'intactagestiónambiental',
 'dygma',
 'inforgesdesarrollodepersonas',
 'ecointelix',
 'fgddesarrollosonline',
 'aloviaconsulting',
 'instraingenieros',
 'kendago',
 'grupopampling',
 'krownbykevinbriceño',
 'edelweissexecutivesearch',
 'keenfolks',
 'ryanair',
 'grupoaldesa',
 'asafedigital',
 'digitalgreen',
 'sommiercenter',
 'tecnoseguretatanoiaservifoc',
 'blueyonder',
 'bysidecar',
 'startpeople',
 'dmedsoftware',
 'atriumselecciónyformaciónsl',
 'switchenergía',
 'rointecalefacción',
 'resaresidenciasdeestudiantes',
 'expleogroup',
 'vtex',
 'ibertechitservices',
 'undisclosed',
 'rroppasmaterialdeportivosl',
 'suremindssolutions',
 'worldpremiumrates',
 'vipirsa',
 'cipheraprosegurcompany',
 'dtcreativos',
 'resilientco',
 'iriumsolucionesysistemas',
 'bandainamcomobile',
 'wwwcardandpaymentjobscom',
 'babblágroup',
 'endivoconsulting',
 'telemira',
 'adelantaco',
 'reqsocksl',
 'senereningeniería',
 'netcompanyintrasoft',
 'claranet',
 'tempotel',
 'ibertech',
 'vanessa',
 'eventflare',
 'sixhunters',
 'javahispano',
 'nspire',
 'vilardebosocialtelecom',
 'westconcomstor',
 'talentareté',
 'globalsavingsgroup',
 'franciscojavier',
 'lumenaltaformerlyclevertech',
 'clubsdir',
 'egaempleo',
 'neuroelectrics',
 '6000accentureslcompany',
 'apsolutgroup',
 'minderest',
 'bnpparibas',
 'merlynmind',
 'devsdatallc',
 'alisys',
 'managingcomposites',
 'preaminternetsl',
 'instede',
 'sysprovider',
 'inycom',
 'pyrmd',
 'elconcheloriginalfoodsa',
 'vrio',
 'klai',
 'covergolimited',
 'meltgroup',
 'carontewebstudiosl',
 'ticjobes',
 'grupocontrolservicios',
 'codigo10solucionesinformaticas',
 'chubbfiresecuritygroup',
 'integratedworldsgmbh',
 'lindtampsprüngli',
 'miteksystems',
 'undergraf',
 'nexo360',
 'acttif',
 'bounsel',
 'humanconsultores',
 'adevinta',
 'resourcegrouprecruitment',
 'unitelsistemadecomunicaciones',
 'advancedtechnologicalknowledge',
 'stratesys',
 'chubb',
 'construcía',
 'vipdistrict',
 'zurichinsurancecompanyltd',
 'publipegacom',
 'logicalisspain',
 'lácteasgarcíabaquero',
 'tmc',
 'oteicconsultinggroupsa',
 'uteradimeralsediputacion',
 'netberrysolutions',
 'featurespace',
 'serviciosplasticossa',
 'automoción',
 'segurcaixa',
 'zaidan',
 'diversey',
 'corvusbellisl',
 'centraldeahorrodelconsumidor',
 'jorge',
 'multiversecomputing',
 'synerlabgroup',
 'aicompgroup',
 'thecignagroup',
 'seleccionit',
 'gregoriopineda',
 'alquadigitalsl',
 'rijkzwaanibericasa',
 'keyfactor',
 'buscadordetrabajojobboard',
 'aqsadvancedqualitysolutionssl',
 'nebulastudiosslu',
 'fenarc',
 'bemycar',
 'tivolilacaleta',
 'hotelbeds',
 'smartassets',
 'eightify',
 'ghenovadigital',
 'grupocor01',
 'fundaciónrandstad',
 'specificgroupspain',
 'tesisga',
 'bbvatechnologyeneuropa',
 'sapindex',
 'nextail',
 'ovhcloud',
 'idoven',
 'alscuentas',
 'tecnoderechosl',
 'beonworldwide',
 'bspexecutive',
 'innovatsn',
 '7experts',
 'omar',
 'biometricvox',
 'thepowerbusinessschool',
 'innovacionriojanadesolucionesitsl',
 'caixabanksa',
 'masymassupermercados',
 'alesonitc',
 'decorarocasl',
 'metricarecruitment',
 'grupocadarso',
 'ineco',
 'tresdotunoconsultoressl',
 'domotekingenieríaprototipadoyformaciónsl',
 'nextdigital',
 'puig',
 'juanmanuel',
 'itapliconsulting',
 'chep',
 'interempleo',
 'octopusenergy',
 'viseo',
 'goldtalent',
 'ctagcentrotecnológicodeautomocióndegalicia',
 'arfimatrading',
 'mamontrealassociates',
 'idcsl',
 'exceltic',
 'europa3gmadrid',
 'digitalgrowthagenciaseoymarketingdigital',
 'tataconsultancyservices',
 'malthusdarwin',
 'suse',
 'sinespecificar',
 'thejumpdigitaltrendsschoolsl',
 'ghenova',
 'mutagency',
 'orbitalrevolution',
 'aygloo',
 'sensudeserviciosydesarrollossl',
 'chemgineeringaustriagmbh',
 'rastreatorcom',
 'eurofirmsgroup',
 'engineerssourcing',
 'zubigroup',
 'sldeautomovilesmajadahonda',
 'designandprojectsinternationaliberiasa',
 'ríosrenovables',
 'surfengineering',
 'lunikexplorersatwork',
 'spartantechnology',
 'sparta',
 'kristalaser',
 'desarrolladorrpajunior',
 'careerwallet',
 'gigster',
 'orenesgrupo',
 'verramobility',
 'merytronic2012',
 'grupoa',
 'creardigital',
 'flowservecorporation',
 'ceiforestudios',
 'estudiocanoarquitecturaslp',
 'ernesto',
 'logicalis',
 'obramat',
 'senovoitltd',
 'demolatam',
 'eaship',
 'winningconsulting',
 'lili',
 'vipnet360',
 'amvsoluciones',
 'seidor',
 'fihocasa',
 'marketingydesarrollo',
 'outlawproductions',
 'repsolsa',
 'vincienergies',
 'dogseguridad',
 'zedis',
 'sandsoft',
 'ambitbst',
 'grupomailcomms',
 'balazs',
 'dinamizadigital',
 'omp',
 'iertec',
 'papernest',
 'ingbanknvsucursalenespaña',
 'openximdexevolutionsl',
 'eulogio',
 'tooltyp',
 'madommanagement',
 'fidesol',
 'mrpglobal',
 'gsmceventprojectmanagementsl',
 'colegiojuanpabloiiparla',
 'makitopromotionalproducts',
 'papelería',
 'desicconsultoratecnológica',
 'platon',
 'grupoproeduca',
 'psicoselección',
 'talio',
 'freshpeople',
 'thewiseseekersl',
 'gamadiconsulting',
 'relocateit',
 'indexeomarketing',
 'chinathreegorgeseuropesa',
 'visiasolutionssl',
 'sandokan',
 'ownplanarquitecturagestión',
 'efrénblancohaircompanysl',
 'shoppinglogistic',
 'cirosip',
 'anandagestionett',
 'anywhere365',
 'transamericacorporation',
 'levysearch',
 'ayudaenacción',
 'adesignstudio',
 'fundacióncarlossimónparalainvestigaciónensaludde',
 'nucleonova',
 '2kmadrid',
 'noneotechsl',
 'empleougr',
 'recann',
 'dominiozero',
 'randnetwork',
 'ms2solucionesdigitales',
 'treelogic',
 'tier1sl',
 'verisure',
 'telefónicasolucionesdeoutsourcing',
 'grupospri',
 'grupadtel',
 'theroofagency',
 'alexavendano',
 'promeritumespaña',
 'necomfire',
 'gaminginnovationgroup',
 'iseazy',
 'beateam',
 'luxoft',
 'utilityconsultingsolutions',
 'ideable',
 'euroconsultsa',
 'ingesisautomatización',
 'q2',
 'pitagorines',
 'dekra',
 'javiermoreno',
 'deudafixreparadoralegalgroupsl',
 'mirantis',
 'realnaut',
 'wayops',
 'epsa',
 'fundaciónamigosdelmuseodelprado',
 'btdgrupo',
 'altendeliverycentrespain',
 'beservicesconsultoraticespecializadaenservicioscloudcomputing',
 'didactia',
 'lbconsultores',
 'emoveereconsulting',
 'iberica',
 'effiwaste',
 'empresadeseleccion',
 'smsdata',
 'izertis',
 'aulasverdesintegralesysinfronteras',
 'arsys',
 'gigistudios',
 'techruiter',
 'betalabinnovation',
 'ekkidentechnologies',
 'thepeoplenetwork',
 'beter',
 'grupoempresarialespañol',
 'papayaglobal',
 'iberianmedia',
 'uiformación',
 'nauticagenova',
 'astrazeneca',
 'valid',
 'dapin',
 'agribioterraorganic',
 'dotgainenconsulting',
 'viotelsl',
 'darren',
 'mercadonatech',
 'avature',
 'gestelcomservicios',
 'reclutamientooutsourcing',
 'compañíalídermundialenserviciosglobalesdeit',
 'worldsensing',
 'payxpert',
 'omnitracs',
 'michaelpageinternationalitaliasrl',
 'addsolutions',
 'empresariocoruna',
 'oxigent',
 'duñas',
 'consultoresit365sl',
 'accionatecnologíayserviciossl',
 'visivalab',
 'cocacolaandinaargentina',
 'get21',
 'digitaltraining',
 'ecam',
 'tufisiocom',
 'enginyeria',
 'laboratoridau',
 'amghumanconsulting',
 'prosafetysoftware',
 'sopremaiberia',
 'matchaco',
 'sigesa',
 'cimne',
 'randstaddigitalespaña',
 'tecnoy',
 'sendaudit',
 'crccajaruralcentral',
 '11onze',
 'enderaplicaciones',
 'tobogganservices',
 'factorlibre',
 'compañiaenmadrid',
 'labalinesa',
 'virtusan',
 'exportadoradatabasesa',
 'cloudpay',
 'selectra',
 'zerohash',
 'cryospain',
 'tusclasesparticulares',
 'trinidad',
 'nucliaaisearchragasaservice',
 'checkinscan',
 'inprosec',
 'talentedinternational',
 'araset',
 'sgaim',
 'fenixgroupinternationalllc',
 'unspecified',
 'talentforjobs',
 '7play',
 'axagroup',
 'aratechlifestyletechnology',
 't2ó',
 'nttdataeuropelatamarquitectosoftware',
 'evolmarketing',
 'digitalmenta',
 'tichconsulting',
 'minsaitindraproduccióndesoftware',
 'thelocal',
 'startup',
 '3000039000alaño',
 'qhumanresources',
 '742425102022',
 'firstmastercloudsl',
 'ribinerf',
 'raiolanetworks',
 'itineretalent',
 'turingprojects',
 'keylandsdg',
 'gsolsolucionesinformáticas',
 'irene',
 'databeacon',
 'cebek',
 'mibee',
 'funiglobal',
 'grupodarainnovacióntecnológica',
 'fnacespaña',
 'cnacitescuelasuperiordeinformática',
 'umatr',
 'servihogarmálaga',
 'wavecontrol',
 'danlukengineering',
 'sistemasdedatossl',
 'qualentum',
 'aviva',
 'crowdstrike',
 'humanselection',
 'cibersare',
 'descantia',
 'informaticaastronmultimediasl',
 'inverto',
 'hrbotfactory',
 'marsh',
 'mediktor',
 'wundermansl',
 'tuio',
 'eurofirmsfoundationeurofirmsgroup',
 'ppgindustries',
 'fullonnet',
 'drakar',
 'aplazame',
 'bengalaspain',
 'rhresearchgroup',
 'mcdonalds',
 'neuroredtmsscm',
 'inserver',
 'mutare',
 'grupopreving',
 'bitpanda',
 'duckduckgo',
 'mcaespaña',
 'digimobil',
 'diarioinformacion',
 'lolagomariz',
 'tecnobravo',
 'seqera',
 'ingroup',
 'techonboard',
 'techniekwerkt',
 'johnsoncontrols',
 'columat',
 'vsistemas',
 'lãberit',
 'zonaphone',
 'enterticket',
 'suprametalsa',
 'dtathesmartmove',
 'taylorhopkinson',
 'kraken',
 'tobestudioexpertosenreformasintegrales',
 'inovace',
 'ingenieriainformaticaempresarial',
 'optimissacapitalmarketsconsulting',
 'aciertaasistencia',
 'metarina',
 'blip',
 'reclutacionweb',
 'bedloop',
 'fullstacklabs',
 'nttspainintelligenttechnologiesandservicesslu',
 'sixtema',
 'abb',
 'belmontegroup',
 'talentofuerte',
 'origenai',
 'opdenergy',
 'surgicalmed',
 '727204082022',
 'opencosmos',
 'serviguidebposl',
 'konecta',
 'cansolenergysolutions',
 'rovergrupo',
 'ayuntamientodeazuquecadehenares',
 'itene',
 'moncisa',
 'quorumselección',
 'dabasystem',
 'vinciconstructionfrance',
 'hapimagmasnou',
 'soainsoftwareassociatessas',
 'yelmocines',
 'pertempserp',
 '360recursoshumanosettsl',
 'grupodeempresasfamiliardedicadaalaprestacióndeserviciosdeprevenciónyconsultoríanormativa',
 'kaizenai',
 'kaplanlanguagesgroupkaplaninternationaleslalpadia',
 'vilaxes',
 'angy',
 'dexisibérica',
 'montarelorecruiting',
 'dempo',
 'velfix',
 's4g',
 'nº',
 'aligntechnology',
 'ricoh',
 'gruponecomplusmemberofaseegroup',
 'entidadfinancieradeámbitonacional',
 'greenrecruitmentcompany',
 'emaisgrupo',
 'educacionit',
 'keinuka',
 'ideasdesdecero',
 'academiatecnicauniversitariasl',
 'nextretgroup',
 'netskope',
 'iriumspain',
 'mkdev',
 'world2fly',
 'davidsonconsulting',
 'flexiplansaett',
 'ikor',
 'enreachlabs',
 'hitachienergyspain',
 'tous',
 'quirónsalud',
 'sintesysglobal',
 'sumauto',
 'tdmsolutions',
 'gprospaindevelopmentsl',
 'atmgrupomaggioli',
 'delsysseidor',
 'gruposecoex',
 'óscar',
 'rithum',
 'betancourt',
 'triangletalentsolutionsrrhhespaña',
 'cobraaeronautics',
 'greene',
 'himalay',
 'neosmart',
 'axiomsoftwaresolutionslimited',
 'mobilots',
 'somenergia',
 'cerquoconsultingsl',
 'wideagency',
 'profesionalindependiente',
 'cattett',
 'homebuddy',
 'noratic',
 'gruposercon',
 'edaggroup',
 'fingercode',
 'essentialistcom',
 'strongpoint',
 'innovery',
 'crazylabs',
 'carlosrodriguezmonsalve',
 'electrotecnicaartechehermanossl',
 'groupeatlantic',
 'intersoftag',
 'accountali',
 'leoni',
 'managementintelligenceconsulting',
 'tkelevadoresespañaslu',
 'ginernet',
 'shenleylionssl',
 'pilatus',
 'ryzlabs',
 'lumensia',
 'factechserviciosinformáticos',
 'wurzelrecruitmentspain',
 'discoteca',
 'aleoestudiodiseñoycomunicacionsl',
 'rightdecisionsasesoresinformáticos',
 'ipraingeniería',
 'bigseo',
 'thigaespaña',
 'vanderlandecareers',
 'mtsglobe',
 'pwcaccelerationcenters',
 ...]

In [28]:
for x in df_company["company_name_lower_no_spaces_no_special_char"]:
    if x == "kenvue":
        print(x)
        break

kenvue

In [29]:
df_company[df_company["company_name_lower_no_spaces_no_special_char"] == "kenvue"]

,company_name,company_name_lower,company_name_lower_no_spaces,company_name_lower_no_spaces_no_special_char
4585,Kenvue,kenvue,kenvue,kenvue

In [30]:
# Verificamos si en "companies" existen ya algunas de df_company

inter_companies = [x for x in companies if x in df_company["company_name_lower_no_spaces_no_special_char"].values]

print(f"Tamaño de 'companies:' {len(companies)}")
print(f"Tamaño de interseccion: {len(inter_companies)}")

Tamaño de 'companies:' 6289
Tamaño de interseccion: 4510

In [31]:
np.array(df["location"].value_counts(dropna = False).index)

array(['Madrid', 'Anywhere', 'Barcelona', 'Spain', 'Valencia', 'Seville',
       'Málaga', 'Bilbao', 'Zaragoza', 'Murcia', 'Tres Cantos',
       'Alicante', 'A Coruña', 'Valladolid', 'Granada', 'Alcobendas',
       'Córdoba', 'Pozuelo de Alarcón', 'Sant Cugat del Vallès',
       'Las Palmas de Gran Canaria', 'Palma', 'Pamplona', 'Vigo',
       'Tarragona', 'Girona', 'Donostia-San Sebastian', 'Catalonia',
       'Getafe', 'Santa Cruz de Tenerife', 'Oviedo', 'Basque Country',
       'Las Rozas de Madrid', 'Albacete', 'Vitoria-Gasteiz', 'Andalusia',
       'Torrejón de Ardoz', 'Gijón', 'Santiago de Compostela', 'León',
       'Paterna', 'Almería', 'Salamanca', 'Asturias', 'Santander',
       'Burgos', 'Castellón de la Plana', 'Lleida',
       'San Sebastián de los Reyes', 'Boadilla del Monte', 'Biscay',
       'Terrassa', 'Cádiz', 'Toledo', 'Martorell',
       "L'Hospitalet de Llobregat", 'Alcala de Henares',
       'San Fernando de Henares', 'Elche', 'Jaén', 'Pontevedra',
       'Ciudad Real', 'Cornellà de Llobregat', 'Valencian Community',
       'Leganés', 'Coslada', 'Navarre', 'Badajoz', 'Cáceres\u200e',
       'Lugo', 'Granollers', 'Alcorcón', 'Guadalajara',
       'Rivas-Vaciamadrid', 'Montserrat', 'Barakaldo', 'Logroño',
       'Badalona', 'Sabadell', 'O Porriño', 'Vic', 'Derio', 'Aranjuez',
       'El Prat de Llobregat', 'Arrasate', 'Ibiza',
       'Palau-solità i Plegamans', 'Cantabria', 'Sant Joan Despí',
       'Balearic Islands', 'Santa Perpètua de Mogoda',
       'Esplugues de Llobregat', 'Majadahonda', 'Huelva', 'Fuenlabrada',
       'Viladecans', 'Riba-roja de Túria', 'Cartagena', nan, 'Galicia',
       'Cerdanyola del Vallès', 'Mataró', 'Marbella', 'Alava', 'Segovia',
       'Rubí', 'Gipuzkoa', 'Ourense', 'Jerez de la Frontera', 'Abrera',
       'Lliçà de Vall', 'Barberà del Vallès', 'Soria', 'Huesca',
       'Palencia', 'Sant Quirze del Vallès', 'Beasain',
       'Castile-La Mancha', 'Manresa', 'Móstoles', 'Villarreal', 'Telde',
       'Cuenca', 'Reus', 'Sant Just Desvern', 'Mérida',
       'Mollet del Vallès', 'Vilanova i la Geltrú', 'Montcada i Reixac',
       'San Cristóbal de La Laguna', 'Oñati', 'Getxo', 'Zamudio',
       'Erandio', 'Hernani', 'Parla', 'Miranda de Ebro',
       'Talavera de la Reina', 'Arganda del Rey', 'Gavà', 'Pinto', 'Nava',
       'Aragon', 'Aviles', 'Andoain', 'Castile and León',
       'Parets del Vallès', 'Albalat dels Sorells', 'Molina de Segura',
       'Barraques', 'Guernica', 'Benidorm', 'Ceuta', 'Ávila\u200e',
       'Noroeste', 'Collado Villalba', 'San Agustín del Guadalix',
       'Boecillo', 'Tordera', 'Castellbisbal', 'Castellví de Rosanes',
       'Meco', 'Lucena', 'Elgoibar', 'Llíria', 'Onda',
       'Mairena del Aljarafe', 'Valls', 'Extremadura',
       'Villaviciosa de Odón', 'Antequera', 'Sarriguren',
       'Colmenar Viejo', 'Humanes de Madrid', 'Quart de Poblet',
       'Valdepeñas', 'Elche Parque Industrial', 'Algete', 'Oña',
       'La Rioja', 'Dos Hermanas', 'Nigrán', 'Vilafranca del Penedès',
       'Ontinyent', 'Alburquerque', 'Torrevieja', 'Zamora', 'Santomera',
       'Torrent', 'Gandia', 'Esparreguera', 'San Cibrao das Viñas',
       'Ferrol', 'Castelldefels', 'Azpeitia',
       'San Lorenzo de El Escorial', 'Figueres', 'Alcalá de Guadaíra',
       'Valdemoro', 'Martos', 'Aldaia', 'Sant Feliu de Llobregat',
       'Bollullos de la Mitación', 'Amorebieta-Etxano', 'Igorre', 'Irun',
       'Alzira', 'Vila-seca', 'Álava', 'Madrigalejo del Monte', 'Alfafar',
       'Sant Boi de Llobregat', 'Écija', 'Fuengirola', 'Sagunto',
       'Estepona', 'Polinyà', 'Tomelloso', 'Xirivella', 'Osona', 'Tudela',
       'Castellón', 'Los Palacios y Villafranca', 'Torrelodones',
       'Lisbon', 'Foios', 'Illescas', 'Azuqueca de Henares', 'San Adrián',
       'Mijas', 'San Fernando', 'Elorrio', 'Santa Cruz de Bezana',
       'Burjassot', 'Las Palmas', 'La Sénia', 'Salou', 'Region of Murcia',
       'San Martín de la Vega', 'Sant Vicent del Raspeig', 'Zaldibar',
       'Cabanillas del Campo', 'Tortosa', 'Maracena', 'Igualada',
       'Sant Esteve Sesrovires', 'Gurb', 'Santa Cruz de Llanera',
       'Viladecavalls', 'Novelda', 'Sant Adrià de Besòs',
       'Bárcena de Cicero', 'Llucmajor', 'Yecla', 'Olesa de Montserrat',
       'Alhaurín de la Torre', 'Montornès del Vallès', 'Lorca', 'Inca',
       "Lliçà d'Amunt", 'Nules', 'Moncofa', 'Santa Coloma de Gramenet',
       'Entresuelo', 'Teruel', 'Albolote', 'Villajoyosa', 'Arona',
       'Vilassar de Dalt', 'Linares', 'Tarancón', 'La Pobla de Vallbona',
       'Abadiño', 'Banyeres de Mariola', 'Puerto de la Cruz', 'Oria',
       'Robledo de Chavela', 'San Bartolomé de Tirajana', 'Algeciras',
       'Castro Urdiales', 'Canary Islands', 'Torrelaguna', 'San Roque',
       'Manacor', 'Ciudadela', 'Culleredo', 'Langreo',
       'Municipality of Alcobendas', 'Casares', 'Santorcaz',
       'Puertollano', 'Albal', 'Ripoll', 'Leioa', 'La Carolina',
       'Montblanc', 'Azkoitia', 'Castalla', 'Villanueva de Tapia',
       'Alberic', 'El Puerto de Santa María', 'Xàtiva', 'Cox', 'Ajalvir',
       'Ripollet', 'Alginet', 'La Garriga', 'Guissona', 'Larrabetzu',
       'Salinetas', 'Benifaió', 'Olmedo', 'San Justo de la Vega',
       'Arteixo', 'Beniparrell', 'Cassà de la Selva', 'Oliva',
       'La Orotava', 'El Viso del Alcor', 'San Juan de Aznalfarache',
       'Sant Feliu de Guíxols', 'Silla', 'Padrón',
       'As Pontes de García Rodríguez', 'Sant Fost de Campsentelles',
       'Molins de Rei', 'Villalbilla', 'Benavente', 'Cintruénigo',
       'Alcover', 'Rota', 'Griñón', 'Don Benito', 'Llinars del Vallès',
       'Astigarraga', 'Roquetas de Mar', 'Zumaia', 'Ciempozuelos',
       'Altea', 'Alcantarilla', 'Martorelles', 'Vilalba', 'Olot', 'Eibar',
       'Bellaterra', 'Redondo', 'Cervera', 'Chinchilla de Montearagón',
       'Loeches', 'Santpedor', 'Benetússer', 'Santa Eulària des Riu',
       'Buñol', 'Ponferrada', 'Moncada', 'Pulpí', 'Mengíbar', 'Argentona',
       'Utebo', 'Zierbena', 'Maspalomas', 'Posada de Valdeón',
       'Valle de Trápaga-Trapagaran', 'Mallabia', "L'Alcora",
       'Campo de Criptana', 'Alcázar de San Juan',
       'Casarrubios del Monte', 'Camas', 'Villena', 'Massanassa',
       'Medellín', 'Torrelavega', 'Torremolinos', 'Torre-Pacheco',
       'Vilagarcía de Arousa', 'Mallén', 'Museros', 'Betanzos', 'Vinaròs',
       'Quer', 'Velilla de San Antonio', 'Alaquàs', 'Tomares',
       'Aretxabaleta', 'El Vendrell', 'Almussafes', 'Almagro', 'Novales',
       'La Pobla de Farnals', 'Lorquí', 'Барселона', 'El Médano',
       'Antzuola', 'Castellar del Vallès', 'Almassora', 'Mutilva Baja',
       'Melilla', 'Ciutadella de Menorca', 'Bormujos', 'Librilla',
       'Benalmádena', "L'Ametlla del Vallès", 'Port de Sagunt', 'Ocaña',
       'Mislata', 'Canet de Mar', 'Valle de Egüés',
       'Malpartida de Plasencia', 'Barbastro', "Sant Joan d'Alacant",
       'Centelles', 'Alboraya', 'Aguadulce', 'Campolivar', 'Ermua',
       'Villanueva de la Jara', 'Alcalá del Valle', 'Les Preses', 'Chiva',
       'Bullas', 'Alalpardo', 'Galdakao', 'Bustarviejo', 'Dolores',
       'Santa María de Cayón', 'Oropesa del Mar', 'Alcàsser', 'Sollana',
       'Constantí', 'Tordesillas', 'Azucaica', 'Abdet', 'Balaguer',
       'San Juan del Puerto', 'Cabezón de la Sal', 'Arnedo', 'Fontanar',
       'A Estrada', 'Godella', 'Aiguaviva', 'Usurbil', 'Bellreguard',
       'Vallès Occidental', 'Collbató', 'La Roca del Vallès', 'Consuegra',
       'Icod de los Vinos', 'Almàssera', 'Betxí', 'Mascaraque', 'Yuncler',
       'Urduliz', 'Fuensalida', 'Zaratamo', 'Almonte',
       'Cabezón de Pisuerga', 'Calahorra', 'Autol', 'Sanchonuño',
       'San Andrés del Rabanedo', 'Belmonte', 'Deba',
       'Sant Quintí de Mediona', 'Puente Genil', 'Ibi', 'Oeiras',
       'Morella', 'Andújar', 'Burguillos', 'Calasparra', 'Burlada',
       'Cervelló', 'Sant Llorenç Savall', 'Zahora', 'Amezketa',
       'Sa Indioteria', 'Sant Vicenç dels Horts', 'Benamejí', 'Ábalos',
       'Sant Cugat Sesgarrigues', 'Premià de Mar', 'Villamalea', 'Berriz',
       'Ólvega', 'Guadix', 'Argamasilla de Calatrava', 'Castro de Rei',
       'Sestao', 'Camariñas', 'El Ballestero', 'Trujillo',
       'Lucena del Puerto', 'Albuixech', "L'Alfàs del Pi", 'Los Molares',
       'Chiclana de la Frontera', "la Vall d'Uixó", 'La Rambla',
       'Portugalete', 'Bétera', 'Corella', 'San Miguel', 'Busot',
       'La Vega', 'Romanyà de la Selva', 'Camargo', 'Benidoleig',
       'El Álamo', 'Puente La Reina – Gares', 'Azuaga', 'Gueñes',
       'Los Cristianos', 'Vega de Infanzones', 'Quart', 'Medio Cudeyo',
       'Marín', 'La Bañeza', 'Golmés', 'Arrankudiaga', 'Malgrat de Mar',
       'Salinas', 'Náquera', 'Conil de la Frontera',
       'La Nava de Santiago', 'Elizondo', 'Cocaño', 'Chantada', 'Calvià',
       'La Penilla', 'Benissa', 'Baza', 'Buñuel',
       'Santa Coloma de Farners', 'Vielha', 'El Goro', 'Amurrio',
       'Masalavés', 'San Pedro del Pinatar', 'Portillo de Toledo',
       'Tegueste', 'Corvera de Asturias', 'Salt', 'Alba de Tormes',
       'Vinyols i els Arcs', 'La Mudarra', 'Besalú', 'Montgat', 'Amer',
       'Capellades', 'Sa Cabaneta', 'Navalcarnero', 'Soto de Viñuelas',
       'O Milladoiro', 'Mejorada del Campo', 'Fraga', 'Tornabous',
       'Iurreta', 'La Rinconada', 'Salvaterra de Miño',
       "Callosa d'en Sarrià", 'Cabrillas', 'Cheste', "L'Albir",
       'Almendralejo', 'Luzón', 'Polán', 'Yunquera de Henares',
       'Finestrat', 'Guardamar del Segura', 'Laudio', 'Coca',
       'San Sebastián de La Gomera', 'Guijuelo',
       'Villanueva de los Infantes', 'Cambrils', 'Navalmoral de la Mata',
       'Alcalá la Real', 'Tías', 'Estaràs', 'Boquiñeni', 'Chinchón',
       'Almansa', 'Мадрид', 'Basauri', 'Berrioplano–Berriobeiti',
       'Arroyomolinos', 'Tembleque', 'Armilla', 'El Masnou', 'Marchamalo',
       'Espinardo', 'Orcoyen', 'Durango', 'Torrejón de la Calzada',
       'Oleiros', 'Aguarón', 'Cuevas del Almanzora', 'Santurtzi',
       'La Algaba', 'Tamaraceite', 'El Astillero', 'Cala', 'Marçà',
       'Adra', 'Els Pallaresos', "La Bisbal d'Empordà", 'Ciudad Rodrigo',
       'Sant Andreu de la Barca', 'Bujalance', 'Navàs', 'Rubiós',
       'Villanueva de la Torre', 'Peligros', 'Santa Coloma de Cervelló',
       'Pineda de Mar', 'Gelves', 'Llocnou de la Corona', 'Puçol',
       'Carbajosa de la Sagrada', 'Bobadilla', 'Bermeo', 'Soto',
       'La Manga', 'Santanyí', 'Iznalloz', 'Cabrerizos', 'Chamartín',
       'Montehermoso', 'Dueñas', 'Llutxent', 'El Puig de Santa Maria',
       'Riudoms', 'As Somozas', 'Partaloa', 'Petrer', 'Rojales',
       'Ajofrín', 'Alfajarín', 'Figueruelas', 'Sax', 'Caldes de Montbui',
       "Pla d'Urgell", 'Palafolls', 'Onzonilla', 'Cistérniga',
       'La Almunia de Doña Godina', 'Santa Maria de Palautordera',
       'Navarrete', 'Tolosa', 'Torrecilla en Cameros', 'La Poveda',
       'Torremejía', 'Milagro', 'Bea', 'El Grao de Castellón',
       'Mequinenza', 'Imárcoain', 'Asturianos', 'Daganzo de Arriba',
       'Ababuj', 'Pedreguer', 'Orihuela', 'Zumarraga', 'Brunete',
       "L'Alcúdia", 'Muskiz', 'Casarrubuelos', 'Vejer de la Frontera',
       'Valdecilla', 'Les Fonts', "L'Eliana", "Corró d'Avall", 'Gáldar',
       'Bueu', 'Tacoronte', "La Seu d'Urgell", 'Pont de Molins', 'Barca',
       'La Pobla de Claramunt', 'Lanzarote', 'Torrellano',
       'Puerto del Rosario', 'Crevillent', 'Aguilas', 'Solsona',
       'Muro de Alcoy', 'Tamón', 'Baños de Rioja', 'Bernedo',
       'Alfara del Patriarca', 'Sant Llorenç des Cardassar', 'Eskoriatza',
       'Monforte de Lemos', 'Las Galletas', 'Mieres del Camino',
       'Vilablareix', 'Uharte-Arakil', 'Ponteareas',
       'Miraflores de la Sierra', 'Pioz', 'Belmonte de Tajo',
       'Los Corrales de Buelna', 'Tavernes de la Valldigna', 'Oiartzun',
       'Churriana de la Vega', 'Vélez-Málaga', 'Castilleja de la Cuesta',
       "Vilobí d'Onyar", 'Caleta de Velez', 'Pontedeume',
       'La Puebla de Cazalla', 'A Baiúca', 'Las Gabias', 'Quintanavides',
       'Bergondo', 'Alhama de Murcia', 'Aguilar de Campoo', 'Seseña',
       'Altzo', 'Mancha Real', 'Adeje', 'Cortes', 'Tudela de Duero',
       'Iznate', 'Tafalla', 'Pedrola', 'Tarazona', 'Motilla del Palancar',
       'Aspe', 'Chapinería', 'Alcoi', 'Paiporta', 'Dénia', 'Narón',
       'Cunit', 'Noáin', 'Carlet', 'Sant Celoni',
       'San Antonio de Benagéber', 'Picanya', 'Cuarte de Huerva',
       'Cardedeu', 'Abaltzisketa', 'Sils', 'Otxandio', 'Manlleu',
       'Algemesí', 'Becerreá', 'Tabaiba', 'Yuncos', 'Maçanet de Cabrenys',
       'Loja', 'Valsequillo de Gran Canaria', 'Sucina',
       'Pilar de la Horadada', 'Villanueva de la Vera',
       'Sant Vicenç de Montalt', 'Loriguilla', 'Montijo', 'Peralta',
       'Fernán Núñez', 'Sedaví', 'Arinaga', 'Riudellots de la Selva',
       'Almuñécar', 'Almoradí', 'Taradell', 'Tui', 'Arucas', 'Tabernilla',
       'Albalate del Arzobispo', 'Los Realejos', 'Playa de las Américas',
       'Blanes', 'Miguelturra', 'Lardero', 'Totana', 'Bellavista',
       'Les Masies de Voltregà', 'Vilafamés', 'Banyoles',
       'Sant Jaume Sesoliveres', 'Hoyo de Manzanares', 'Santa Oliva',
       'El Campello', 'Municipality of San Fernando de Henares', 'Neda',
       'Honrubia de la Cuesta', 'Calp', 'Alhama de Granada',
       'La Cala del Moral', 'Sant Pere de Ribes', 'Mataporquera',
       'Alhaurín el Grande', 'Province of Ourense',
       'Villanueva del Ariscal', 'La Codoñera', 'Sallent', 'Beniel',
       'La Pineda', 'Aljaraque', 'Pastrana', 'Sant Francesc Xavier',
       'Atarfe', 'A Fraga', 'Costa Adeje', 'Pollença', 'Canovelles',
       'Montilla', 'La Zubia', 'Santa Pola', 'Monte'], dtype=object)

In [32]:
df.fillna(np.nan).replace([np.nan], [None]).to_csv("bigquery_1.csv", index = False)

In [33]:
df.to_csv("bigquery_1.csv", index = False)